### PR TITLE
tile provider management

### PR DESCRIPTION
**Pull request by ThomasHalwax**
The user will be able to manage the tile providers available to ODIN via the "View->Manage Tile Providers ..." menu.

I've created a second react app that does not conflict with the primary app. As of today the menu entries will not be recreated dynamically. In order to reload the tile-providers.json the user will have to restart the application.

### CODE REVIEW

**Comment by dehmer** [comment]
I encountered some issue:
* For some reason two additional entries are added to 'View' menu after configuring tile providers through the new window. These entries are 'Show Tab Bar' and 'Show All Tabs'. There are inserted right at the top of the menu, before 'Tile Provider'. I have yet to find out why and when this happens.
* Hitting 'Reload' in new tile provider window will render it empty except for the '+' button.
* Subdomain other than 'abc' (Leaflet default) seem to not be supported [https://leafletjs.com/reference-1.6.0.html#tilelayer-option]. I was not able to configure Basemap AT which requires '1234' subdomains. 
* Is it possible to dynamically updated View menu depending on new configuration? It seems restarting the application is required to take effect.

**Comment by ThomasHalwax** [comment]
ad subdomains: You are right, leaflet uses default values for the subdomain. In order to provide other values, one need to provide custom values as a parameter for the ```TileLayer``` function:
```L.tileLayer('http://{s}.somedomain.com/{foo}/{z}/{x}/{y}.png', {foo: 'bar'});```

Fortunately basemap.at uses a clever load balancer that works with the default domain name:

```https://maps.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png```

**Comment by ThomasHalwax** [comment]
> * Hitting 'Reload' in new tile provider window will render it empty except for the '+' button.

The reason for this is the communication pattern used. The main process sends the list of tile providers the the renderer only once (when the renderer window is created).

**Comment by ThomasHalwax** [comment]
> * For some reason two additional entries are added to 'View' menu after configuring tile providers through the new window. These entries are 'Show Tab Bar' and 'Show All Tabs'. There are inserted right at the top of the menu, before 'Tile Provider'. I have yet to find out why and when this happens.

I can not reproduce this issue:
Bildschirmfoto 2020-03-07 um 14 39 24

**Comment by ThomasHalwax** [comment]
> * Is it possible to dynamically updated View menu depending on new configuration? It seems restarting the application is required to take effect.

Currently Electron does not support dynamic changes on menu entries. The only way to add/remove at runtime is to call ```setApplicationMenu``` again. 

> Menu.getApplicationMenu()

> Returns Menu | null - The application menu, if set, or null, if not set.

> Note: The returned Menu instance doesn't support dynamic addition or removal of menu items. Instance properties can still be dynamically modified.

Source: [Electron Documentation Menu Class](https://www.electronjs.org/docs/api/menu)

**Comment by ThomasHalwax** [comment]
Since we have an improved version for 0.6.0/ol I close this PR.

**Pull request closed without merging**
