### PR TITLE
basemap management and activity

### PR DESCRIPTION
**Pull request by ThomasHalwax**
This PR enables management of basemaps of type XYZ or WMTS. Since the latest commit has been merged the appropriate ActivityItem for choosing the current basemap is also included.

### CODE REVIEW

**Comment by dehmer** [comment]
Issue: List of available basemaps is not updated after new basemap was created.

**Comment by ThomasHalwax** [comment]
> Issue: List of available basemaps is not updated after new basemap was created.

Are you talking about the Activity Panel? At the moment you need to close/open the panel to update the list.

**Comment by dehmer** [comment]
WMTS: Is it possible to update preview in step 2, thus making step 3 unnecessary?

**Comment by dehmer** [comment]
Yes, the Activity Panel content is not updated. Can this be fixed?

**Comment by ThomasHalwax** [comment]
> WMTS: Is it possible to update preview in step 2, thus making step 3 unnecessary?

I'll take a look, but maybe we can defer this optimization for the next iteration. We also need to improve error handling. WMTS is a beast and using n tile providers comes up with n+1 different possibilities to fail.

**Comment by ThomasHalwax** [comment]
> Yes, the Activity Panel content is not updated. Can this be fixed?

Updating the panel is currently not implemented. I'll take a look.

**Comment by ThomasHalwax** [comment]
> Yes, the Activity Panel content is not updated. Can this be fixed?

Has been fixed!

**Comment by ThomasHalwax** [comment]
Additional changes:
* BasemapList changes preferences
* map registers for changes in preferences and changes the basemap accordingly
* BasemapList changes when sources change

**Pull request merged**
