### PR TITLE
Assign references to documents and links to features

### LINKED ISSUE #369: assign external documents to a feature
Besides the map there are other documents like ORBAT, written orders, pictures and many others that need to be considered for the current situation. Currently the user needs to remember where those documents are located in order to open them.

I suggest that users can assign an arbitrary number of linked documents to a feature. This could be done by dropping a local document or web URL to the properties panel of the currently selected feature. The links (URIs) to the documents will be persisted. When a user selects a feature all assigned links are shown in the properties panel. By clicking on a link ODIN executes the OS _open_ command and delegates control to the operations system (finding the assigned application to the document and open it). The effect would be the same as if the user had opened the document in the filesystem explorer/finder.

Of course all CRUD operations for assigned document links (add, edit, remove link) need to be supported. Since the panel is already filled with MilStd properties we could introduce tabs to separate these concerns (feature properties from assigned documents).

### PR DESCRIPTION
**Pull request by ThomasHalwax**
Resolves #369 

This PR introduces the ability to assign references to documents stored in the (local) filesystem and/or links to web resources.

In order to do so the feature property panel has been refactored to make use of tabs. The primary one holds all the symbol props and the secondary allows adding via drag&drop and deleting references. Currently there is no editing functionality.

The number of assigned references is indicated by making use of badges:

image

When a references is clicked is is NOT opened inside ODIN but by asking the OS to do so. Since some references may be harmful the user needs to permit the operation:
Bildschirmfoto 2021-03-16 um 19 28 42

__Please note that opening external documents is not permitted by electron/chrome when ODIN is running in DEV mode (```npm run hot```).__

### CODE REVIEW

**Comment by dehmer** [comment]
* References are exported along with a JSON layer. Is this intentional?
* Opening a reference after renaming/delete it shows System Message 'Opening URL **succeeded'**. This is a little misleading.
* Executables can be added (and opened) as references. Maybe this could lead to serious security issues (especially when they are exported) - tested on macOS. 
* Folders/directories can be added (and opened) as references. Is this a security concern?
* Adding '~/Desktop/zustand - npm.webloc' (Safari link to https://www.npmjs.com/package/zustand) results in **two** entries 'https://www.npmjs.com' and 'zustand - npm.webloc'

In general, I'm not sure if we should export and potentially distribute local file system paths, since this reveals parts of the users file system organisation.

**Comment by ThomasHalwax** [comment]
> * References are exported along with a JSON layer. Is this intentional?

Yes, sharing references to common documents is intentional.

> * Opening a reference after renaming/delete it shows System Message 'Opening URL **succeeded'**. This is a little misleading.

This is related to electron's mechanism to open references/links. I'll review this.

> * Executables can be added (and opened) as references. Maybe this could lead to serious security issues (especially when they are exported) - tested on macOS.

The first revision of this PR had some checks and denied opening executable files. This worked well on platforms where FS permissions are set as needed (RWX). Unfortunately MS Windows handles permissions differently and almost any file is flagged as executable. So checking for X does not make any sense.

> * Folders/directories can be added (and opened) as references. Is this a security concern?

I don't thinks so because the default action for a folder is to open it in the OS explorer/finder.

> * Adding '~/Desktop/zustand - npm.webloc' (Safari link to https://www.npmjs.com/package/zustand) results in **two** entries 'https://www.npmjs.com' and 'zustand - npm.webloc'

OK, I will take a look.

> In general, I'm not sure if we should export and potentially distribute local file system paths, since this reveals parts of the users file system organisation.

After all it's about security and privacy. Not a single action is executed without the user's intent. The user is required to confirm if she wants to allow opening a FS resource or web link.

**Comment by ThomasHalwax** [comment]
One of the first versions also limited references to known mime types. But again this did not work on MS Windows because even for office documents like DOCX, XSLX, etc. the mime type was empty.

**Comment by ThomasHalwax** [comment]
@dehmer I fixed the misleading success message although the target of the reference does not exist.

Can you please tell me how to reproduce

> Adding '~/Desktop/zustand - npm.webloc' (Safari link to https://www.npmjs.com/package/zustand) results in two entries 'https://www.npmjs.com' and 'zustand - npm.webloc'

**Comment by dehmer** [comment]
To reproduce webloc issue:
* macOS: 10.15.7, Safari: 14.0.3
* Open link 'https://www.google.com/?client=safari' in Safari
* **Drag link from address bar (icon) to desktop**
* Drag Google.webloc from desktop to feature references in ODIN

NOTE: Dragging link directly from browser ODIN seems to work fine.

**Comment by ThomasHalwax** [comment]
This happens because the ```dataTransfer``` object contains a file AND an item. Since I can not tell if the one is related to the other I add them both.

**Comment by dehmer** [comment]
I think, that's not a biggy.
Both entries open the page. Not many users will use this feature for macOS. And in those rare cases, the user can delete one of the two references.

From your perspective, Is this PR now ready to roll?

**Comment by ThomasHalwax** [comment]
OK, thank you. I will do some minor modifications (wrapping the delete icon with an IconButton) and then I'd merge the PR.

**Comment by dehmer** [comment]
Fine for me. 👍

**Pull request merged**
