### PR TITLE
basemap/opacity

### PR DESCRIPTION
**Pull request by ThomasHalwax**
PR introduces the ability to change the opacity of basemaps. This allows users to create an even better appearance of the resulting basemap by stacking them and change the opacity individually.

image

### CODE REVIEW

**Comment by dehmer** [comment]
Is there a chance, we can make layer names use multiple lines, so they would not collide with icons?

Screenshot 2020-05-25 at 17 41 24

**Comment by dehmer** [comment]
I'd suggest a slightly different approach for showing opacity slider.
If layer item would maintain a selection state, opacity component could always reflect the opacity value of the selected layer. This would also make the 'settings' button go away and make more room for layer name.
See: https://material-ui.com/components/lists/#selected-listitem

**Comment by ThomasHalwax** [comment]
> I'd suggest a slightly different approach for showing opacity slider.
> If layer item would maintain a selection state, opacity component could always reflect the opacity value of the selected layer. This would also make the 'settings' button go away and make more room for layer name.
> See: https://material-ui.com/components/lists/#selected-listitem

First I went with the tune icon was because a MUI button destroys the drag&drop capability of the ListItem. Now the text is clickable (behaves like a button) to make it clear that something will happen if the user clicks here.

**Comment by ThomasHalwax** [comment]
> Is there a chance, we can make layer names use multiple lines, so they would not collide with icons?
> 
> Screenshot 2020-05-25 at 17 41 24

fixed

**Pull request merged**
