### PR TITLE
0.6.0/palette

### PR DESCRIPTION
**Pull request by dehmer**
Feature palette for supported geometries:
* point
* polygon
* line
* line-2pt

Screenshot 2020-05-28 at 09 46 32

NOTE: PR also contains changes in 'active layer' handling.

### CODE REVIEW

**Comment by ThomasHalwax** [comment]
When a layer is the "active layer" the "visibility" icon gets disabled:

image

**Comment by ThomasHalwax** [comment]
I don't think users will be happy with the palette. On first start it is empty and one might think it's broken. The user is forced to know at least a part of the hierarchy code/name of a symbol.

I'd suggest to either
* provide predefined search patterns that can easily be activated like "ground", "infantry", ... and activate at least one at startup
* show the least specialized symbol available ("unit", "equipment", ...) instead of an empty list

Also, instead of "Search..." in the input field I'd give more explicit examples like "Search for "ground", "missile", "LD", ...

**Comment by ThomasHalwax** [comment]
Some of the symbols don't seem to work correctly. I.e. "Purple Kill Box" let's you select one point on the map but the the input mode ends immediately and the properties panel gets opened - without any symbol on the map.

**Comment by ThomasHalwax** [comment]
After playing around for a while I had a waring from node:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 MAP_DRAW listeners added to [EventEmitter]
```

**Comment by dehmer** [comment]
> After playing around for a while I had a warning from node:
> 
> ```
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 MAP_DRAW listeners added to [EventEmitter]
> ```

Strange. That listener should only be registered once inside map/effect.
Can you remember what you did while playing?

**Comment by dehmer** [comment]
> I don't think users will be happy with the palette. On first start it is empty and one might think it's broken. The user is forced to know at least a part of the hierarchy code/name of a symbol.
> 
> I'd suggest to either
> 
> * provide predefined search patterns that can easily be activated like "ground", "infantry", ... and activate at least one at startup
> * show the least specialized symbol available ("unit", "equipment", ...) instead of an empty list
> 
> Also, instead of "Search..." in the input field I'd give more explicit examples like "Search for "ground", "missile", "LD", ...

Agreed. We can later think about re-adding predefined feature sets or a list of recently used features, which also is empty at the beginning. To give users at least some hints for now, I suggest some descriptive texts:

Screenshot 2020-05-29 at 07 11 34

**Comment by dehmer** [comment]
I am not able to reproduce the listener leak. What we can do is limit max listener count for 'evented' to 1 to trigger the error faster.

**Comment by dehmer** [comment]
Just got this

> react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>     in FeaturePalette (created by Activities)
> 

I am investigating...

**Comment by dehmer** [comment]
Listener leak is fixed. It also was responsible for updating unmounted palette component.

**Comment by dehmer** [comment]
> Some of the symbols don't seem to work correctly. I.e. "Purple Kill Box" let's you select one point on the map but the the input mode ends immediately and the properties panel gets opened - without any symbol on the map.

I identified 85 feature descriptors which are obviously wrong, i.e. POINT geometry for non-point features. This is because of MIP mapping I used to create the descriptors. I have still to figure out how to improve this situation.

**Pull request merged**
