### PR TITLE
0.6.0/layer-list

### PR DESCRIPTION
**Pull request by dehmer**
PR Introduces

* Create new, empty layer (no undo)
* Delete selected layer (with undo)
* Clipboard ops for selected layer: cut, copy, paste (with undo)
* Duplicate layer (convenience, with undo)
* Rename layer (only through ENTER key on layer (with undo)
* Natural sort order for layers and features
* Disable lock/hide layer for empty layers

### CODE REVIEW

**Comment by ThomasHalwax** [comment]
Creating a new layer does not scroll to the new entry. So when a layer with a lot of entries is open (let say its name is "Maritime") the new layer is inserted as 'New Layer" which shifts it to the end of the layer list. Unfortunately its out of the visible scope of the list.
I'd suggest to scroll the list to the new entry.

**Comment by ThomasHalwax** [comment]
Using Undo it's possible to get into trouble:

1) create two new layers: 'New Layer' and 'New Layer (1)'
2) Delete 'New Layer'
3) create a new layer which will create another layer names 'New Layer'
4) do CMD-Z, which will undo the Delete 'New Layer' command from step 2)

You now have two layers named 'New Layer'. You are able to delete one of them, but an attempt to delete the second one will throw an error (only visible in the console).
Restarting ODIN will fix the problem.

**Comment by dehmer** [comment]
> Creating a new layer does not scroll to the new entry. So when a layer with a lot of entries is open (let say its name is "Maritime") the new layer is inserted as 'New Layer" which shifts it to the end of the layer list. Unfortunately its out of the visible scope of the list.
> I'd suggest to scroll the list to the new entry.

Git it. I will see what's possible with MUI.

**Comment by ThomasHalwax** [comment]
I think I found a serious bug. In order to reproduce it you need a layer with a few features:

1) expand the layer
2) select a feature and delete it
3) select the layer itself and delete it
4) press CMD-Z 3 times and ODIN will die with our old async error:

```Error: async hook stack has become corrupted (actual: 49, expected: 0)```

**Comment by dehmer** [comment]
fixed: https://github.com/syncpoint/ODIN/pull/291#issuecomment-628561279

**Comment by dehmer** [comment]
> I think I found a serious bug. In order to reproduce it you need a layer with a few features...

Jep! Undoing layer delete will assign new layer id. Undeleted feature won't find its original layer.
Any idea how the expected behavior could look like?
Undoing a delete should probably not change identity. I have to think about this.

**Comment by dehmer** [comment]
fixed: https://github.com/syncpoint/ODIN/pull/291#issuecomment-628566777

**Comment by ThomasHalwax** [comment]
> > Creating a new layer does not scroll to the new entry. So when a layer with a lot of entries is open (let say its name is "Maritime") the new layer is inserted as 'New Layer" which shifts it to the end of the layer list. Unfortunately its out of the visible scope of the list.
> > I'd suggest to scroll the list to the new entry.
> 
> Got it. I will see what's possible with MUI.

OK, maybe this should also work the a user uses UNDO for layers.

**Comment by dehmer** [comment]
I don't see an easy solution for the "Scroll to" problem. This is probably possible with direct DOM access, but this will take some time to get right.
If this is not a PR blocker, we could file an issue to address this later.

**Pull request merged**
